### ISSUE TITLE
upstream multisig backend

### ISSUE THREAD

**Issue by aleem1314** [vitwit/resolute#1020]
Upstream multisig backend updates to `master` branch

- [ ] Upstream backend updates from `dev` to `master` branch
- [ ] Add authorization to delete multisig account(only the creator can delete multisig account).

**Comment by anilcse** [comment]
@aleem1314 is this done?

**Comment by Hemanthghs** [comment]
> @aleem1314 is this done?

Its done but there was an issue in the backend, fixed it now.

**Comment by anilcse** [comment]
Can we close it? Let's review and close all the completed issues
