### ISSUE TITLE
bug: IBC transactions not working

### ISSUE THREAD

**Issue by Teja2045** [vitwit/resolute#1168]
I was trying to do ibc transactions but it's not letting me do it and showing tooltip "Metamask doesn't suppport IBC" even though I was on Keplr

![Screenshot from 2024-02-19 14-50-59](https://github.com/vitwit/resolute/assets/106052623/07f2c195-29fc-441a-b972-64ee0ab6d3e3)

**Comment by Hemanthghs** [comment]
Addressed in this PR https://github.com/vitwit/resolute/pull/1170
