### ISSUE TITLE
reset state on account change

### ISSUE THREAD

**Issue by aleem1314** [vitwit/resolute#534]
# Summary

Reset redux state and redirect to main page on account change in keplr wallet.

**Comment by Teja2045** [comment]
should I dispatch resetState reducers of all sub states (except wallet) in Home page?

**Comment by aleem1314** [comment]
> should I dispatch resetState reducers of all sub states (except wallet) in Home page?

Yes. You should reset all the slices to initial state (except wallet) . Just call this function inside keplr wallet change event listener.

``` js

const resetAllSlices = () => {
  Object.values(store.getState()).forEach((slice) => {
    if (slice.reset) {
      store.dispatch(slice.reset());
    }
  });
};

```
