### ISSUE TITLE
wallet: add leap wallet support

### ISSUE THREAD

**Issue by aleem1314** [vitwit/resolute#593]
Reference: https://docs.leapwallet.io/cosmos/for-dapps-connect-to-leap/add-leap-to-existing-keplr-integration

**Comment by Teja2045** [comment]
- added window.wallet which will be dynamically decided ( window.wallet = window.keplr or window.wallet = window.leap )
- changed window.offlineSigner(chainID) to window.wallet.offlineSigner(chainID) for all transactions
