### ISSUE TITLE
staking: invalid staking rewards for umee network

### ISSUE THREAD

**Issue by aleem1314** [vitwit/resolute#688]
# Summary

This account has `umee1uvcj5e2j2hdrta7hcya409klqwf000mt7qkxvg` `6.55UMEE` pending rewards. Overview page is showing `9,000.846UMEE`.

**Comment by Hemanthghs** [comment]
In distributionSlice while calculating totalRewards other ibc token rewards are also getting added that why its showing incorrect rewards.

![image](https://github.com/vitwit/resolute/assets/56679184/faa89207-796f-45b5-a271-b4891beaa267)

Shall we only consider the native chain rewards?
